/**
 * Authentic Kolhapuri Khanawal Hotel POS Expense Master
 * 13 Structured Categories, Subcategories, Vendor/Staff Payee Tracking, and Frequency Metadata
 */

import {
  ExpenseCategoryConfig,
  ExpenseSubcategoryConfig,
  MasterExpenseCategory,
  ExpenseRecord,
} from "@/types/expenses";

export const khanawalExpenseCategories: ExpenseCategoryConfig[] = [
  {
    id: "exp-cat-food",
    name: "Food & Raw Materials",
    localName: "अन्न व कच्चा माल",
    description: "Daily fresh vegetables, chicken, mutton, kirana, milk, spices, and thali accompaniments",
    iconName: "Utensils",
    colorClass: "bg-emerald-50 text-emerald-800 border-emerald-300",
  },
  {
    id: "exp-cat-fuel",
    name: "Fuel",
    localName: "इंधन (गॅस व कोळसा)",
    description: "Commercial LPG gas cylinders and tandoor/bhatti charcoal",
    iconName: "Flame",
    colorClass: "bg-amber-50 text-amber-800 border-amber-300",
  },
  {
    id: "exp-cat-packaging",
    name: "Packaging",
    localName: "पॅकेजिंग साहित्य",
    description: "Parcel boxes, silver foil, thali covers, and dustbin bags",
    iconName: "Package",
    colorClass: "bg-blue-50 text-blue-800 border-blue-300",
  },
  {
    id: "exp-cat-cleaning",
    name: "Cleaning & Sanitation",
    localName: "स्वच्छता व सॅनिटायझेशन",
    description: "Floor phenyl, Nirma detergent, liquid dishwash, wipers, and towels",
    iconName: "Sparkles",
    colorClass: "bg-cyan-50 text-cyan-800 border-cyan-300",
  },
  {
    id: "exp-cat-staff",
    name: "Staff & Labour",
    localName: "कर्मचारी व मजुरी",
    description: "Porter wages, bhandi wali payments, staff salaries, advances, and deductions",
    iconName: "Users",
    colorClass: "bg-purple-50 text-purple-800 border-purple-300",
  },
  {
    id: "exp-cat-utilities",
    name: "Utilities & Connectivity",
    localName: "युटिलिटीज (वायफाय, वीज, पाणी)",
    description: "Restaurant WiFi fiber, electricity, water bills, and mobile recharges",
    iconName: "Wifi",
    colorClass: "bg-indigo-50 text-indigo-800 border-indigo-300",
  },
  {
    id: "exp-cat-repairs",
    name: "Repairs & Maintenance",
    localName: "दुरुस्ती व देखभाल",
    description: "Gas stove repair, deep freezer compressor, electrical, plumbing, and blade sharpening",
    iconName: "Wrench",
    colorClass: "bg-rose-50 text-rose-800 border-rose-300",
  },
  {
    id: "exp-cat-kitchen-supplies",
    name: "Kitchen Supplies",
    localName: "किचन साहित्य व भांडी",
    description: "Utensils, bhandi saman, tissue boxes, knife sharpening, and locks",
    iconName: "CookingPot",
    colorClass: "bg-stone-50 text-stone-800 border-stone-300",
  },
  {
    id: "exp-cat-office",
    name: "Office & Administrative",
    localName: "कार्यालयीन खर्च",
    description: "Xerox, photocopy, billing registers, stationery, tape, and first aid supplies",
    iconName: "FileText",
    colorClass: "bg-sky-50 text-sky-800 border-sky-300",
  },
  {
    id: "exp-cat-equipment",
    name: "Equipment & Setup",
    localName: "उपकरणे व सेटअप",
    description: "Plywood, dining furniture, lights, storage mats, and hardware purchases",
    iconName: "Layers",
    colorClass: "bg-orange-50 text-orange-800 border-orange-300",
  },
  {
    id: "exp-cat-supplier",
    name: "Supplier / Vendor Payments",
    localName: "सप्लायर व व्हेंडर पेमेंट्स",
    description: "Periodic vendor advances, invoice payments, and supplier settlements",
    iconName: "Coins",
    colorClass: "bg-teal-50 text-teal-800 border-teal-300",
  },
  {
    id: "exp-cat-misc",
    name: "Miscellaneous / Petty Expenses",
    localName: "किरकोळ व इतर खर्च (Kirkol)",
    description: "Petty cash, auto transport, small emergency kitchen spends, and incidental Kirkol",
    iconName: "Wallet",
    colorClass: "bg-yellow-50 text-yellow-800 border-yellow-300",
  },
  {
    id: "exp-cat-staff-welfare",
    name: "Staff Welfare",
    localName: "कर्मचारी कल्याण",
    description: "Daily staff tea, morning nashta, staff meals, and emergency medical support",
    iconName: "HeartHandshake",
    colorClass: "bg-pink-50 text-pink-800 border-pink-300",
  },
];

export const khanawalExpenseSubcategories: ExpenseSubcategoryConfig[] = [
  // ── 1. Food & Raw Materials ───────────────────────────────────────
  { name: "Chapati / Bhakri", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "चपाती / भाकरी" },
  { name: "Bhaji Pala", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "भाजीपाला / ताजी भाजी" },
  { name: "Chicken", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "चिकन (ताजे मटण/पोल्ट्री)" },
  { name: "Mutton", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "मटण (बोकड मटण)" },
  { name: "Kirana", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "किराणा सामान" },
  { name: "Milk", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "दूध" },
  { name: "Dahi", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "दही" },
  { name: "Butter", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "बटर / लोणी" },
  { name: "Groundnut", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "शेंगदाणे" },
  { name: "Jeera", category: "Food & Raw Materials", defaultFrequency: "OCCASIONAL", localName: "जिरे" },
  { name: "Chat Masala", category: "Food & Raw Materials", defaultFrequency: "OCCASIONAL", localName: "चाट मसाला" },
  { name: "Mint / Sauf", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "पुदिना / बडीशेप" },
  { name: "Khobara / Coconut", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "सुके / ओले खोबरे" },
  { name: "Khobara Powder", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "खोबरे पावडर" },
  { name: "Badam", category: "Food & Raw Materials", defaultFrequency: "OCCASIONAL", localName: "बदाम" },
  { name: "Kaju Badam", category: "Food & Raw Materials", defaultFrequency: "OCCASIONAL", localName: "काजू बदाम" },
  { name: "Paneer", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "पनीर" },
  { name: "Cream", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "मलाई / फ्रेश क्रीम" },
  { name: "Ghee", category: "Food & Raw Materials", defaultFrequency: "OCCASIONAL", localName: "शुद्ध तूप" },
  { name: "Jilebi", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "जिलेबी" },
  { name: "Sweets", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "मिठाई" },
  { name: "Nashta", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "सकाळचा नाश्ता" },
  { name: "Soup", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "सूप साहित्य" },
  { name: "Drinking Water", category: "Food & Raw Materials", defaultFrequency: "DAILY", localName: "पिण्याचे पाणी" },
  { name: "Water Bottles", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "मिनरल वॉटर बाटल्या" },
  { name: "Cold Drinks", category: "Food & Raw Materials", defaultFrequency: "FREQUENT", localName: "कोल्ड ड्रिंक्स" },

  // ── 2. Fuel ───────────────────────────────────────────────────────
  { name: "Coal / Charcoal", category: "Fuel", defaultFrequency: "FREQUENT", localName: "तंदूर कोळसा" },
  { name: "Gas / Cylinder", category: "Fuel", defaultFrequency: "OCCASIONAL", localName: "कमर्शियल एलपीजी सिलिंडर" },

  // ── 3. Packaging ──────────────────────────────────────────────────
  { name: "Packaging Material", category: "Packaging", defaultFrequency: "DAILY", localName: "पार्सल कंटेनर्स / पिशव्या" },
  { name: "Foil", category: "Packaging", defaultFrequency: "FREQUENT", localName: "अ‍ॅल्युमिनिअम फॉइल" },
  { name: "Dustbin Bags", category: "Packaging", defaultFrequency: "FREQUENT", localName: "कचरा पिशव्या" },
  { name: "Tissue Paper", category: "Packaging", defaultFrequency: "DAILY", localName: "टिश्यू पेपर" },

  // ── 4. Cleaning & Sanitation ──────────────────────────────────────
  { name: "Phenyl", category: "Cleaning & Sanitation", defaultFrequency: "FREQUENT", localName: "फिनाईल" },
  { name: "Nirma / Detergent", category: "Cleaning & Sanitation", defaultFrequency: "FREQUENT", localName: "डिटर्जंट पावडर" },
  { name: "Liquid Dishwash", category: "Cleaning & Sanitation", defaultFrequency: "FREQUENT", localName: "डिशवॉश लिक्विड" },
  { name: "Cleaning Materials", category: "Cleaning & Sanitation", defaultFrequency: "FREQUENT", localName: "स्वच्छता साहित्य" },
  { name: "Gloves", category: "Cleaning & Sanitation", defaultFrequency: "OCCASIONAL", localName: "रबर हँडग्लोज" },
  { name: "Wiper", category: "Cleaning & Sanitation", defaultFrequency: "OCCASIONAL", localName: "फ्लोअर वायपर" },
  { name: "Towel", category: "Cleaning & Sanitation", defaultFrequency: "OCCASIONAL", localName: "पुसण्याचे टॉवेल" },
  { name: "Sanitization Material", category: "Cleaning & Sanitation", defaultFrequency: "OCCASIONAL", localName: "सॅनिटायझर" },

  // ── 5. Staff & Labour ─────────────────────────────────────────────
  { name: "Porter", category: "Staff & Labour", defaultFrequency: "DAILY", localName: "हमाल / कुली मजुरी" },
  { name: "Bhandi Bai / Bhandi Wali", category: "Staff & Labour", defaultFrequency: "DAILY", localName: "भांडी वाली मावशी मजुरी" },
  { name: "Kitchen Staff Payment", category: "Staff & Labour", defaultFrequency: "FREQUENT", localName: "किचन स्टाफ पेमेंट" },
  { name: "Staff Advance", category: "Staff & Labour", defaultFrequency: "OCCASIONAL", localName: "स्टाफ अ‍ॅडव्हान्स" },
  { name: "Staff Salary", category: "Staff & Labour", defaultFrequency: "MONTHLY", localName: "स्टाफ पगार" },
  { name: "Staff Food / Nashta", category: "Staff & Labour", defaultFrequency: "DAILY", localName: "स्टाफ जेवण / नाश्ता" },
  { name: "Staff Deduction", category: "Staff & Labour", defaultFrequency: "OCCASIONAL", localName: "स्टाफ कपात" },
  { name: "Staff Reimbursement", category: "Staff & Labour", defaultFrequency: "OCCASIONAL", localName: "स्टाफ खर्च परतावा" },
  { name: "Staff Miscellaneous Payment", category: "Staff & Labour", defaultFrequency: "OCCASIONAL", localName: "स्टाफ इतर पेमेंट" },

  // ── 6. Utilities & Connectivity ───────────────────────────────────
  { name: "WiFi / Internet", category: "Utilities & Connectivity", defaultFrequency: "MONTHLY", localName: "वायफाय ब्रॉडबँड बिल" },
  { name: "Electricity", category: "Utilities & Connectivity", defaultFrequency: "MONTHLY", localName: "वीज बिल" },
  { name: "Water Bill", category: "Utilities & Connectivity", defaultFrequency: "MONTHLY", localName: "पाणी बिल" },
  { name: "Gas Pipeline / Bill", category: "Utilities & Connectivity", defaultFrequency: "MONTHLY", localName: "गॅस बिल" },
  { name: "Telephone / Mobile", category: "Utilities & Connectivity", defaultFrequency: "MONTHLY", localName: "मोबाईल रिचार्ज" },
  { name: "Other Utilities", category: "Utilities & Connectivity", defaultFrequency: "OCCASIONAL", localName: "इतर युटिलिटीज" },

  // ── 7. Repairs & Maintenance ──────────────────────────────────────
  { name: "Gas Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "गॅस शेगडी दुरुस्ती" },
  { name: "Freezer / Refrigerator Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "फ्रीज / कॉम्प्रेसर दुरुस्ती" },
  { name: "Electrical Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "इलेक्ट्रिकल वायरिंग दुरुस्ती" },
  { name: "Plumbing Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "नळ / प्लंबिंग काम" },
  { name: "Kitchen Equipment Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "किचन उपकरणे दुरुस्ती" },
  { name: "Furniture Repair", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "टेबल / खुर्ची दुरुस्ती" },
  { name: "Blade Sharpening", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "सुरी / पाती धार लावणे" },
  { name: "General Maintenance", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "दुकान देखभाल" },
  { name: "Other Repairs", category: "Repairs & Maintenance", defaultFrequency: "OCCASIONAL", localName: "इतर दुरुस्ती" },

  // ── 8. Kitchen Supplies ───────────────────────────────────────────
  { name: "Kitchen Supplies", category: "Kitchen Supplies", defaultFrequency: "FREQUENT", localName: "किचन साहित्य" },
  { name: "Kitchen Utensils", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "किचन भांडी" },
  { name: "Utensils", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "स्टील वाट्या / ताटे" },
  { name: "Bhandi Saman", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "भांडी सामान" },
  { name: "Tissue Box", category: "Kitchen Supplies", defaultFrequency: "FREQUENT", localName: "टिश्यू बॉक्स" },
  { name: "Locks", category: "Kitchen Supplies", defaultFrequency: "ONE_TIME", localName: "कुलूप / चावी" },
  { name: "Register", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "किचन रजिस्टर" },
  { name: "Tape", category: "Kitchen Supplies", defaultFrequency: "FREQUENT", localName: "चिकटपट्टी" },
  { name: "Mat", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "मॅट / पायपुसणी" },
  { name: "First Aid Supplies", category: "Kitchen Supplies", defaultFrequency: "OCCASIONAL", localName: "प्रथमोपचार किट" },

  // ── 9. Office & Administrative ────────────────────────────────────
  { name: "Xerox / Photocopy", category: "Office & Administrative", defaultFrequency: "FREQUENT", localName: "झेरॉक्स / प्रिंट" },
  { name: "Registers", category: "Office & Administrative", defaultFrequency: "OCCASIONAL", localName: "हिशोब वह्या / रजिस्टर्स" },
  { name: "Printing", category: "Office & Administrative", defaultFrequency: "OCCASIONAL", localName: "प्रिंटिंग" },
  { name: "Stationery", category: "Office & Administrative", defaultFrequency: "FREQUENT", localName: "पेन / स्टॅशनरी" },
  { name: "Office Supplies", category: "Office & Administrative", defaultFrequency: "OCCASIONAL", localName: "कार्यालयीन साहित्य" },
  { name: "Miscellaneous Administrative Expense", category: "Office & Administrative", defaultFrequency: "OCCASIONAL", localName: "इतर अ‍ॅडमिन खर्च" },

  // ── 10. Equipment & Setup ─────────────────────────────────────────
  { name: "Plywood", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "प्लायवूड" },
  { name: "Furniture", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "फर्निचर" },
  { name: "Kitchen Equipment", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "किचन मशिनरी" },
  { name: "Utensils / Equipment Purchase", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "नवीन भांडी खरेदी" },
  { name: "Lights", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "लाइट्स / एलईडी बल्ब" },
  { name: "Refrigerator / Freezer", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "डीप फ्रीजर खरेदी" },
  { name: "Storage Equipment", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "स्टोरेज रॅक्स" },
  { name: "Mats", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "डोअर मॅट्स" },
  { name: "Hardware", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "हार्डवेअर साहित्य" },
  { name: "Restaurant Setup Material", category: "Equipment & Setup", defaultFrequency: "ONE_TIME", localName: "हॉटेल सेटअप साहित्य" },

  // ── 11. Supplier / Vendor Payments ────────────────────────────────
  { name: "Vendor Payment", category: "Supplier / Vendor Payments", defaultFrequency: "FREQUENT", localName: "व्हेंडर पेमेंट" },
  { name: "Vendor Advance", category: "Supplier / Vendor Payments", defaultFrequency: "OCCASIONAL", localName: "व्हेंडर अ‍ॅडव्हान्स" },
  { name: "Supplier Advance", category: "Supplier / Vendor Payments", defaultFrequency: "OCCASIONAL", localName: "सप्लायर अ‍ॅडव्हान्स" },
  { name: "Supplier Invoice Payment", category: "Supplier / Vendor Payments", defaultFrequency: "FREQUENT", localName: "सप्लायर बिल पेमेंट" },
  { name: "Supplier Balance Payment", category: "Supplier / Vendor Payments", defaultFrequency: "OCCASIONAL", localName: "शिल्लक बाकी पेमेंट" },

  // ── 12. Miscellaneous / Petty Expenses ────────────────────────────
  { name: "Kirkol", category: "Miscellaneous / Petty Expenses", defaultFrequency: "OCCASIONAL", localName: "किरकोळ खर्च (Kirkol)" },
  { name: "Petty Cash", category: "Miscellaneous / Petty Expenses", defaultFrequency: "DAILY", localName: "पेटी कॅश" },
  { name: "Small Kitchen Expense", category: "Miscellaneous / Petty Expenses", defaultFrequency: "DAILY", localName: "लहान किचन खर्च" },
  { name: "Small Transport Expense", category: "Miscellaneous / Petty Expenses", defaultFrequency: "FREQUENT", localName: "रिक्षा / वाहतूक खर्च" },
  { name: "Small Repair Expense", category: "Miscellaneous / Petty Expenses", defaultFrequency: "OCCASIONAL", localName: "लहान दुरुस्ती" },
  { name: "Other Small Expense", category: "Miscellaneous / Petty Expenses", defaultFrequency: "OCCASIONAL", localName: "इतर किरकोळ खर्च" },

  // ── 13. Staff Welfare ─────────────────────────────────────────────
  { name: "Staff Tea", category: "Staff Welfare", defaultFrequency: "DAILY", localName: "स्टाफ चहा" },
  { name: "Staff Nashta", category: "Staff Welfare", defaultFrequency: "DAILY", localName: "स्टाफ नाश्ता" },
  { name: "Staff Food", category: "Staff Welfare", defaultFrequency: "DAILY", localName: "स्टाफ जेवण" },
  { name: "Staff Medical", category: "Staff Welfare", defaultFrequency: "OCCASIONAL", localName: "स्टाफ औषधोपचार" },
  { name: "Staff Welfare", category: "Staff Welfare", defaultFrequency: "OCCASIONAL", localName: "स्टाफ कल्याण" },
];

export const knownExpenseParties = [
  "Mahesh",
  "Raju Chicken Supplier",
  "Sandip",
  "Ranjit",
  "Bhandi Bai",
  "Maushi",
  "Wastad",
  "Airtel Fiber Internet",
  "MSEDCL Electricity",
  "Kolhapur Municipal Corporation",
  "Bharat Gas Agency",
  "HP Commercial Gas",
  "BlueStar Refrigeration Services",
  "Prakash Kirana Mart",
  "Shetkari Mandi Bhaji Pala",
  "Gokul Milk Dairy",
  "Kolhapur Packaging Store",
  "Local Auto Transport",
];

export const initialKhanawalExpenses: ExpenseRecord[] = [
  {
    id: "exp-1",
    date: "2026-09-14",
    category: "Food & Raw Materials",
    subcategory: "Bhaji Pala",
    item: "Fresh vegetable mandi purchase for thali gravies",
    party: "Shetkari Mandi Bhaji Pala",
    paidTo: "Shetkari Mandi Bhaji Pala",
    amount: 1450,
    paymentMethod: "CASH",
    frequency: "DAILY",
    notes: "Tomatoes, onions, coriander, green chilies for thecha",
    isReviewed: true,
    createdAt: "2026-09-14T06:30:00Z",
  },
  {
    id: "exp-2",
    date: "2026-09-14",
    category: "Food & Raw Materials",
    subcategory: "Chapati / Bhakri",
    item: "Daily fresh jowar bhakri and chapati supply",
    party: "Maushi",
    paidTo: "Maushi",
    amount: 600,
    paymentMethod: "CASH",
    frequency: "DAILY",
    notes: "30 Jowar Bhakri + 20 Chapati for lunch service",
    isReviewed: true,
    createdAt: "2026-09-14T10:00:00Z",
  },
  {
    id: "exp-3",
    date: "2026-09-14",
    category: "Staff & Labour",
    subcategory: "Porter",
    item: "Unloading raw material sacks & gas cylinders",
    party: "Porter",
    paidTo: "Porter",
    amount: 150,
    paymentMethod: "CASH",
    frequency: "DAILY",
    notes: "Heavy mandi delivery unloading",
    isReviewed: true,
    createdAt: "2026-09-14T07:15:00Z",
  },
  {
    id: "exp-4",
    date: "2026-09-14",
    category: "Fuel",
    subcategory: "Coal / Charcoal",
    item: "Tandoor and sigdi hard coal sack",
    party: "Sandip",
    paidTo: "Sandip",
    amount: 850,
    paymentMethod: "CASH",
    frequency: "FREQUENT",
    notes: "For tandoor kebabs and rassa bhatti",
    isReviewed: true,
    createdAt: "2026-09-14T08:30:00Z",
  },
  {
    id: "exp-5",
    date: "2026-09-14",
    category: "Staff & Labour",
    subcategory: "Staff Advance",
    item: "Emergency mid-month advance",
    party: "Ranjit",
    paidTo: "Ranjit",
    amount: 1000,
    paymentMethod: "UPI",
    frequency: "OCCASIONAL",
    notes: "Family medical need, to be adjusted against salary",
    isReviewed: true,
    createdAt: "2026-09-14T14:20:00Z",
  },
  {
    id: "exp-6",
    date: "2026-09-13",
    category: "Repairs & Maintenance",
    subcategory: "Freezer / Refrigerator Repair",
    item: "BlueStar walk-in freezer gas charging & thermostat replacement",
    party: "BlueStar Refrigeration Services",
    paidTo: "BlueStar Refrigeration Services",
    amount: 3800,
    paymentMethod: "UPI",
    frequency: "OCCASIONAL",
    notes: "Deep freezer temperature stabilized at -18C",
    isReviewed: true,
    createdAt: "2026-09-13T16:00:00Z",
  },
  {
    id: "exp-7",
    date: "2026-09-13",
    category: "Utilities & Connectivity",
    subcategory: "WiFi / Internet",
    item: "Monthly commercial gigabit fiber connection for POS & UPI",
    party: "Airtel Fiber Internet",
    paidTo: "Airtel Fiber Internet",
    amount: 1500,
    paymentMethod: "UPI",
    frequency: "MONTHLY",
    notes: "Includes static IP for cloud backup & online QR",
    isReviewed: true,
    createdAt: "2026-09-13T11:00:00Z",
  },
  {
    id: "exp-8",
    date: "2026-09-13",
    category: "Miscellaneous / Petty Expenses",
    subcategory: "Kirkol",
    item: "Emergency auto fare for urgent kitchen delivery",
    party: "Local Auto Transport",
    paidTo: "Local Auto Transport",
    amount: 120,
    paymentMethod: "CASH",
    frequency: "OCCASIONAL",
    notes: "Brought missing spice packets from market",
    isReviewed: true,
    createdAt: "2026-09-13T12:45:00Z",
  },
];
