/**
 * Real Operational Sample Data for Kolhapuri Khanawal in Baner, Pune
 * Total recorded sample transactions from 04/09/2026 to 07/09/2026: ₹59,201
 */

import {
  Supplier,
  QuickPurchaseEntry,
  SupplierAdvanceRecord,
  SupplierPaymentRecord,
  PriceHistoryRecord,
  DailyClosingSnapshot,
} from "@/types/inventory";
import {
  Employee,
  AttendanceRecord,
  StaffAdvanceRecord,
  KhanawalTask,
  HotelEquipment,
  KhanawalReminder,
  RestaurantNotification,
  OfficeGroupOrder,
} from "@/types/domain";
import { ExpenseRecord, CashLedgerEntry, UPILedgerEntry } from "@/types/billing";

// ── 1. SUPPLIERS ──────────────────────────────────────────────────
export const initialSuppliers: Supplier[] = [
  {
    id: "sup-raju-chicken",
    name: "Raju Poultry Farm",
    phone: "+91 98221 01010",
    suppliedItems: ["Fresh Chicken (कोंबडी)", "Eggs"],
    totalPurchased: 8360,
    totalPaid: 8360,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Daily delivery at 7:30 AM fresh chicken",
    isActive: true,
    createdAt: "2024-01-15",
  },
  {
    id: "sup-prakash-mutton",
    name: "Prakash Goat Mutton Mart",
    phone: "+91 98222 02020",
    suppliedItems: ["Fresh Mutton (बोकडाचे मटण)"],
    totalPurchased: 18280,
    totalPaid: 18280,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Grade-1 fresh goat meat with marrow bones",
    isActive: true,
    createdAt: "2024-02-01",
  },
  {
    id: "sup-mahesh-bhakri",
    name: "Mahesh Bhakri & Chapati Kendra",
    phone: "+91 98223 03030",
    suppliedItems: ["Jowar Bhakri (भाकरी)", "Fresh Chapati (चपाती)"],
    totalPurchased: 4400,
    totalPaid: 4400,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Wood-fired traditional Jowar bhakri twice daily",
    isActive: true,
    createdAt: "2024-03-10",
  },
  {
    id: "sup-swastik-kirana",
    name: "Swastik Kirana & Spices",
    phone: "+91 98224 04040",
    suppliedItems: ["Indrayani Rice", "Toor Dal", "Groundnut Oil", "Kolhapuri Masala", "Goda Masala"],
    totalPurchased: 8300,
    totalPaid: 8300,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Wholesale delivery from Market Yard",
    isActive: true,
    createdAt: "2024-01-20",
  },
  {
    id: "sup-datta-dairy",
    name: "Datta Dairy & Kokum House",
    phone: "+91 98225 05050",
    suppliedItems: ["Dahi (दही)", "Fresh Milk", "Kokum Extract", "White Butter"],
    totalPurchased: 1570,
    totalPaid: 1570,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Rich buffalo milk and fresh set curd",
    isActive: true,
    createdAt: "2024-04-05",
  },
  {
    id: "sup-baner-gas",
    name: "Baner Commercial Gas & Fuel",
    phone: "+91 98226 06060",
    suppliedItems: ["Commercial 19kg LPG Cylinder", "Charcoal"],
    totalPurchased: 2885,
    totalPaid: 2885,
    currentAdvance: 0,
    outstandingPayable: 0,
    notes: "Emergency delivery within 45 mins",
    isActive: true,
    createdAt: "2024-01-10",
  },
];

// ── 2. REAL SAMPLE TRANSACTIONS (04/09/2026 to 07/09/2026 = ₹59,201) ─
// Breakdown:
// 04/09/2026: ₹9,355
// 05/09/2026: ₹19,358
// 06/09/2026: ₹11,703
// 07/09/2026: ₹18,785
// Total: ₹59,201
export const initialPurchases: QuickPurchaseEntry[] = [
  // ── 04/09/2026 (₹9,355 total) ──────────────────────────────────
  {
    id: "pur-20260904-01",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    quantity: 5,
    unit: "kg",
    rate: 370,
    totalAmount: 1850,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-04",
    notes: "Morning batch fresh chicken",
  },
  {
    id: "pur-20260904-02",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    quantity: 4,
    unit: "kg",
    rate: 750,
    totalAmount: 3000,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-04",
    notes: "Fresh goat mutton",
  },
  {
    id: "pur-20260904-03",
    supplierId: "sup-mahesh-bhakri",
    supplierName: "Mahesh Bhakri & Chapati Kendra",
    ingredientId: "ing-chapati",
    ingredientName: "Bhakri & Chapati Lot",
    quantity: 90,
    unit: "piece",
    rate: 10,
    totalAmount: 900,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-04",
    notes: "60 Bhakris + 30 Chapatis",
  },
  {
    id: "pur-20260904-04",
    supplierId: "sup-baner-gas",
    supplierName: "Baner Commercial Gas & Fuel",
    ingredientId: "ing-gas",
    ingredientName: "19kg Commercial LPG Cylinder",
    quantity: 1,
    unit: "piece",
    rate: 1885,
    totalAmount: 1885,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-04",
    notes: "Kitchen main cylinder refill",
  },

  // ── 05/09/2026 (₹19,358 total) ─────────────────────────────────
  {
    id: "pur-20260905-01",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    quantity: 6,
    unit: "kg",
    rate: 380,
    totalAmount: 2280,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-05",
    notes: "Weekend lunch prep chicken",
  },
  {
    id: "pur-20260905-02",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    quantity: 7,
    unit: "kg",
    rate: 760,
    totalAmount: 5320,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-05",
    notes: "High footfall weekend meat batch",
  },
  {
    id: "pur-20260905-03",
    supplierId: "sup-swastik-kirana",
    supplierName: "Swastik Kirana & Spices",
    ingredientId: "ing-oil",
    ingredientName: "Groundnut Oil 15L + Kolhapuri Spices",
    quantity: 1,
    unit: "box",
    rate: 3450,
    totalAmount: 3450,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-05",
    notes: "15L Tin Oil + Spices stock",
  },
  {
    id: "pur-20260905-04",
    supplierId: "sup-datta-dairy",
    supplierName: "Datta Dairy & Kokum House",
    ingredientId: "ing-dairy",
    ingredientName: "Fresh Dahi & Buffalo Milk",
    quantity: 10,
    unit: "kg",
    rate: 68,
    totalAmount: 680,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-05",
    notes: "Dahi for raita + milk for tea",
  },
  {
    id: "pur-20260905-05",
    supplierId: "sup-baner-gas",
    supplierName: "Baner Commercial Gas & Fuel",
    ingredientId: "ing-charcoal",
    ingredientName: "Babul Charcoal for Chulha",
    quantity: 25,
    unit: "kg",
    rate: 40,
    totalAmount: 1000,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-05",
    notes: "Charcoal bag for tandoor/chulha",
  },

  // ── 06/09/2026 (₹11,703 total) ─────────────────────────────────
  {
    id: "pur-20260906-01",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    quantity: 5,
    unit: "kg",
    rate: 378,
    totalAmount: 1890,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-06",
    notes: "Prompt test example: 5kg @ ₹378/kg from Raju",
  },
  {
    id: "pur-20260906-02",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    quantity: 5,
    unit: "kg",
    rate: 760,
    totalAmount: 3800,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-06",
    notes: "Fresh goat mutton",
  },

  // ── 07/09/2026 (₹18,785 total) ─────────────────────────────────
  {
    id: "pur-20260907-01",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    quantity: 6,
    unit: "kg",
    rate: 390,
    totalAmount: 2340,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-07",
    notes: "Price increase from ₹378 to ₹390 (+3.1%)",
  },
  {
    id: "pur-20260907-02",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    quantity: 8,
    unit: "kg",
    rate: 770,
    totalAmount: 6160,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-07",
    notes: "Baner IT lunch surge supply",
  },
  {
    id: "pur-20260907-03",
    supplierId: "sup-swastik-kirana",
    supplierName: "Swastik Kirana & Spices",
    ingredientId: "ing-rice",
    ingredientName: "Indrayani Rice 50kg bag + Masalas",
    quantity: 1,
    unit: "box",
    rate: 4850,
    totalAmount: 4850,
    paymentMethod: "UPI",
    paymentStatus: "PAID",
    date: "2026-09-07",
    notes: "50kg authentic Indrayani rice + Goda masala",
  },
  {
    id: "pur-20260907-04",
    supplierId: "sup-datta-dairy",
    supplierName: "Datta Dairy & Kokum House",
    ingredientId: "ing-dairy",
    ingredientName: "Fresh Dahi & Milk Supply",
    quantity: 13,
    unit: "kg",
    rate: 68.46,
    totalAmount: 890,
    paymentMethod: "CASH",
    paymentStatus: "PAID",
    date: "2026-09-07",
    notes: "Dahi + milk for solkadhi & tea",
  },
];

// ── 3. STRUCTURED EXPENSES & REPAIRS ──────────────────────────────
export const initialExpenses: ExpenseRecord[] = [
  // 04/09/2026
  {
    id: "exp-20260904-01",
    date: "2026-09-04",
    category: "FOOD_PURCHASE",
    item: "Fresh Bhaji, Kanda & Lemon from APMC Mandi",
    amount: 720,
    paidTo: "APMC Market Pashan",
    paymentMethod: "CASH",
    notes: "Daily vegetables and onions",
    isReviewed: true,
    createdAt: "2026-09-04T08:30:00Z",
  },
  {
    id: "exp-20260904-02",
    date: "2026-09-04",
    category: "CLEANING",
    item: "Commercial Phenyl & Dishwashing liquid",
    amount: 450,
    paidTo: "Baner Wholesale Traders",
    paymentMethod: "CASH",
    notes: "Daily floor and utensil cleaning materials",
    isReviewed: true,
    createdAt: "2026-09-04T10:00:00Z",
  },
  {
    id: "exp-20260904-03",
    date: "2026-09-04",
    category: "KITCHEN",
    item: "Foil Rolls & Table Paper Napkins",
    amount: 550,
    paidTo: "Ganesh Disposables",
    paymentMethod: "CASH",
    notes: "Parcel wrapping foil and tissue boxes",
    isReviewed: true,
    createdAt: "2026-09-04T11:00:00Z",
  },

  // 05/09/2026
  {
    id: "exp-20260905-01",
    date: "2026-09-05",
    category: "REPAIR",
    item: "Commercial Deep Freezer Compressor & Gas Leak Repair",
    amount: 3800,
    paidTo: "CoolTech Refrigeration Baner",
    paymentMethod: "CASH",
    notes: "CRITICAL REPAIR: BlueStar freezer stopped cooling. New capacitor + R134a gas recharge.",
    isReviewed: true,
    createdAt: "2026-09-05T14:30:00Z",
  },
  {
    id: "exp-20260905-02",
    date: "2026-09-05",
    category: "MAINTENANCE",
    item: "Commercial Waterproof Plywood & Partition Labour",
    amount: 2400,
    paidTo: "Shree Ganesh Timber & Carpentry",
    paymentMethod: "UPI",
    notes: "Repaired water-damaged service counter plywood and service hatch.",
    isReviewed: true,
    createdAt: "2026-09-05T16:00:00Z",
  },
  {
    id: "exp-20260905-03",
    date: "2026-09-05",
    category: "FOOD_PURCHASE",
    item: "Kanda (Onion) & Fresh Coriander Bag",
    amount: 428,
    paidTo: "APMC Pashan",
    paymentMethod: "CASH",
    notes: "Extra onions for chicken & mutton rassa base",
    isReviewed: true,
    createdAt: "2026-09-05T09:15:00Z",
  },

  // 06/09/2026
  {
    id: "exp-20260906-01",
    date: "2026-09-06",
    category: "WIFI",
    item: "Airtel Commercial Gigabit Fiber Internet Bill",
    amount: 1500,
    paidTo: "Airtel Broadband Services",
    paymentMethod: "UPI",
    notes: "Monthly business WiFi for POS terminal, UPI soundbox, and kitchen KDS",
    isReviewed: true,
    createdAt: "2026-09-06T10:30:00Z",
  },
  {
    id: "exp-20260906-02",
    date: "2026-09-06",
    category: "EQUIPMENT",
    item: "Stainless Steel Thalis & Water Jugs (Set of 8)",
    amount: 1650,
    paidTo: "Mahalaxmi Steel Mart",
    paymentMethod: "UPI",
    notes: "Replaced 8 dented copper-bottom thalis with heavy stainless steel",
    isReviewed: true,
    createdAt: "2026-09-06T12:00:00Z",
  },
  {
    id: "exp-20260906-03",
    date: "2026-09-06",
    category: "FOOD_PURCHASE",
    item: "Vegetables, Lemon, Ginger & Kanda",
    amount: 860,
    paidTo: "Mandi Vendor",
    paymentMethod: "CASH",
    notes: "Fresh produce for sunday service",
    isReviewed: true,
    createdAt: "2026-09-06T08:00:00Z",
  },
  {
    id: "exp-20260906-04",
    date: "2026-09-06",
    category: "CLEANING",
    item: "Heavy Dustbin Liners, Wiper & Nirma",
    amount: 503,
    paidTo: "Baner Kirana",
    paymentMethod: "CASH",
    notes: "Wet waste bags and scrubber pads",
    isReviewed: true,
    createdAt: "2026-09-06T17:00:00Z",
  },

  // 07/09/2026 (Today)
  {
    id: "exp-20260907-01",
    date: "2026-09-07",
    category: "MAINTENANCE",
    item: "Commercial Kitchen Exhaust Fan Servicing & Degreasing",
    amount: 1200,
    paidTo: "Omkar Electric Works",
    paymentMethod: "CASH",
    notes: "Cleaned heavy grease and oiled motor bearings",
    isReviewed: true,
    createdAt: "2026-09-07T11:30:00Z",
  },
  {
    id: "exp-20260907-02",
    date: "2026-09-07",
    category: "MAINTENANCE",
    item: "Dining Hall Emergency Lights & Switch Replacement",
    amount: 950,
    paidTo: "Poonam Electricals",
    paymentMethod: "CASH",
    notes: "Replaced 2 flicker tubes and main toggle switch",
    isReviewed: true,
    createdAt: "2026-09-07T13:00:00Z",
  },
  {
    id: "exp-20260907-03",
    date: "2026-09-07",
    category: "FOOD_PURCHASE",
    item: "Fresh Veggies, Kanda, Lemon & Ginger",
    amount: 895,
    paidTo: "APMC Mandi",
    paymentMethod: "CASH",
    notes: "Fresh ingredients for tambda/pandhra rassa seasoning",
    isReviewed: true,
    createdAt: "2026-09-07T08:15:00Z",
  },
  {
    id: "exp-20260907-04",
    date: "2026-09-07",
    category: "UNCLASSIFIED",
    item: "Local Market Miscellaneous Shopping",
    amount: 450,
    paidTo: "Local Vendor",
    paymentMethod: "CASH",
    notes: "Emergency purchase by helper — receipts to be verified by manager",
    isReviewed: false,
    createdAt: "2026-09-07T15:45:00Z",
  },
];

// ── 4. SUPPLIER ADVANCES & ACCOUNTING SEPARATION ──────────────────
// Note: Prompt Rule: Advance must never be double counted with invoice!
// Mahesh Advance = ₹2,000 on 05/09.
// Later Chapati Invoice = ₹2,100 on 07/09.
// System calculation: Advance ₹2,000, Invoice ₹2,100 -> Remaining payable ₹100.
export const initialSupplierAdvances: SupplierAdvanceRecord[] = [
  {
    id: "sadv-mahesh-01",
    supplierId: "sup-mahesh-bhakri",
    supplierName: "Mahesh Bhakri & Chapati Kendra",
    amount: 2000,
    date: "2026-09-05",
    paymentMethod: "CASH",
    notes: "Advance payment for 4 days Jowar Bhakri and Chapati supply",
    adjustedAmount: 2000,
    remainingAdvance: 0,
  },
];

export const initialSupplierPayments: SupplierPaymentRecord[] = [
  {
    id: "spay-mahesh-settle-01",
    supplierId: "sup-mahesh-bhakri",
    supplierName: "Mahesh Bhakri & Chapati Kendra",
    amount: 100,
    date: "2026-09-07",
    paymentMethod: "CASH",
    notes: "Invoice ₹2,100 less Advance ₹2,000 = Balance ₹100 paid in Cash",
  },
];

// ── 5. STAFF ADVANCES ─────────────────────────────────────────────
export const initialStaffAdvances: StaffAdvanceRecord[] = [
  {
    id: "stf-adv-suresh",
    employeeId: "emp-suresh",
    employeeName: "Suresh Maharaj (Head Cook)",
    amount: 1500,
    date: "2026-09-06",
    recoveredAmount: 0,
    status: "PENDING",
    notes: "Medical advance requested by cook",
  },
  {
    id: "stf-adv-mahesh",
    employeeId: "emp-bandu",
    employeeName: "Bandu Patil (Bhakri Specialist)",
    amount: 2000,
    date: "2026-09-07",
    recoveredAmount: 0,
    status: "PENDING",
    notes: "Festival advance requested by Bandu",
  },
];

// ── 6. EMPLOYEES & STAFF ROSTER ───────────────────────────────────
export const initialEmployees: Employee[] = [
  {
    id: "emp-suresh",
    name: "Suresh Maharaj",
    role: "Cook",
    phone: "+91 98227 01001",
    joiningDate: "2024-03-01",
    baseSalary: 28000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-bandu",
    name: "Bandu Patil",
    role: "Chapati/Bhakri",
    phone: "+91 98227 01002",
    joiningDate: "2024-05-15",
    baseSalary: 18000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-rahul",
    name: "Rahul Shinde",
    role: "Waiter",
    phone: "+91 98227 01003",
    joiningDate: "2024-08-01",
    baseSalary: 14000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-nitin",
    name: "Nitin Jadhav",
    role: "Waiter",
    phone: "+91 98227 01004",
    joiningDate: "2025-01-10",
    baseSalary: 13000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-sachin",
    name: "Sachin More",
    role: "Kitchen Helper",
    phone: "+91 98227 01005",
    joiningDate: "2025-02-01",
    baseSalary: 12000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-priya",
    name: "Priya Kulkarni",
    role: "Cashier",
    phone: "+91 98227 01006",
    joiningDate: "2025-03-01",
    baseSalary: 16000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-sunita",
    name: "Sunita Bai",
    role: "Cleaning",
    phone: "+91 98227 01007",
    joiningDate: "2024-04-01",
    baseSalary: 11000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
  {
    id: "emp-vikram",
    name: "Vikram Patil",
    role: "Manager",
    phone: "+91 98227 01008",
    joiningDate: "2023-11-01",
    baseSalary: 32000,
    salaryType: "MONTHLY",
    status: "ACTIVE",
  },
];

// ── 7. TODAY'S STAFF ATTENDANCE ───────────────────────────────────
export const initialAttendance: AttendanceRecord[] = [
  { id: "att-1", employeeId: "emp-suresh", employeeName: "Suresh Maharaj", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:15:00Z" },
  { id: "att-2", employeeId: "emp-bandu", employeeName: "Bandu Patil", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:20:00Z" },
  { id: "att-3", employeeId: "emp-rahul", employeeName: "Rahul Shinde", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:45:00Z" },
  { id: "att-4", employeeId: "emp-nitin", employeeName: "Nitin Jadhav", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:50:00Z" },
  { id: "att-5", employeeId: "emp-sachin", employeeName: "Sachin More", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:30:00Z" },
  { id: "att-6", employeeId: "emp-priya", employeeName: "Priya Kulkarni", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T08:00:00Z" },
  { id: "att-7", employeeId: "emp-sunita", employeeName: "Sunita Bai", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:10:00Z" },
  { id: "att-8", employeeId: "emp-vikram", employeeName: "Vikram Patil", date: "2026-09-07", status: "PRESENT", markedAt: "2026-09-07T07:00:00Z" },
];

// ── 8. HOTEL EQUIPMENT & MAINTENANCE LOG ──────────────────────────
export const initialEquipment: HotelEquipment[] = [
  {
    id: "eq-freezer",
    name: "BlueStar Commercial 400L Deep Freezer",
    category: "FREEZER",
    purchaseDate: "2024-01-10",
    repairHistory: [
      {
        date: "2026-09-05",
        description: "Emergency Compressor & Gas Recharge (CoolTech Baner)",
        cost: 3800,
        vendor: "CoolTech Refrigeration Baner",
      },
    ],
    totalRepairCost: 3800,
    nextServiceDate: "2026-12-05",
    status: "OPERATIONAL",
  },
  {
    id: "eq-gas-range",
    name: "3-Burner Commercial Gas Range & High Pressure Valves",
    category: "GAS",
    purchaseDate: "2024-02-15",
    repairHistory: [
      {
        date: "2026-08-10",
        description: "High pressure brass valve and gas pipe replacement",
        cost: 850,
        vendor: "Baner Gas Agency",
      },
    ],
    totalRepairCost: 850,
    nextServiceDate: "2026-10-10",
    status: "OPERATIONAL",
  },
  {
    id: "eq-exhaust",
    name: "Commercial Heavy Duty Kitchen Exhaust Hood & Blower",
    category: "KITCHEN",
    purchaseDate: "2024-03-01",
    repairHistory: [
      {
        date: "2026-09-07",
        description: "Exhaust fan motor bearing oiling and duct cleaning",
        cost: 1200,
        vendor: "Omkar Electric Works",
      },
    ],
    totalRepairCost: 1200,
    nextServiceDate: "2026-11-07",
    status: "OPERATIONAL",
  },
  {
    id: "eq-lights",
    name: "Dining Hall LED Fixtures & Emergency Backup",
    category: "LIGHTS",
    purchaseDate: "2024-01-05",
    repairHistory: [
      {
        date: "2026-09-07",
        description: "Replaced faulty switch & 2 LED batten lights",
        cost: 950,
        vendor: "Poonam Electricals",
      },
    ],
    totalRepairCost: 950,
    nextServiceDate: "2027-01-05",
    status: "OPERATIONAL",
  },
  {
    id: "eq-wifi",
    name: "Airtel Commercial Gigabit WiFi Router",
    category: "WIFI",
    purchaseDate: "2024-01-01",
    repairHistory: [],
    totalRepairCost: 0,
    nextServiceDate: "2026-10-01",
    status: "OPERATIONAL",
  },
  {
    id: "eq-water",
    name: "Commercial RO Purifier 50 LPH",
    category: "WATER",
    purchaseDate: "2024-03-20",
    repairHistory: [
      {
        date: "2026-08-01",
        description: "Carbon & sediment filter candle change",
        cost: 1400,
        vendor: "AquaPure Baner",
      },
    ],
    totalRepairCost: 1400,
    nextServiceDate: "2026-11-01",
    status: "OPERATIONAL",
  },
];

// ── 9. OPERATIONAL TASKS WITH PRIORITY ─────────────────────────────
export const initialKhanawalTasks: KhanawalTask[] = [
  {
    id: "task-1",
    title: "Check Deep Freezer temperature (< -18°C) before lunch rush",
    assignedTo: "Suresh Maharaj",
    priority: "CRITICAL",
    dueDate: "2026-09-07T11:00:00Z",
    status: "PENDING",
    reminder: true,
    createdAt: "2026-09-07T07:30:00Z",
  },
  {
    id: "task-2",
    title: "Buy fresh Chicken (6kg) from Raju Poultry for dinner",
    assignedTo: "Vikram Patil",
    priority: "HIGH",
    dueDate: "2026-09-07T16:30:00Z",
    status: "PENDING",
    reminder: true,
    createdAt: "2026-09-07T08:00:00Z",
  },
  {
    id: "task-3",
    title: "Collect 80 hot Jowar Bhakris from Mahesh Kendra at 12:30 PM",
    assignedTo: "Rahul Shinde",
    priority: "HIGH",
    dueDate: "2026-09-07T12:30:00Z",
    status: "PENDING",
    reminder: true,
    createdAt: "2026-09-07T08:00:00Z",
  },
  {
    id: "task-4",
    title: "Reconcile daily Cash Drawer & UPI balances before closing",
    assignedTo: "Priya Kulkarni",
    priority: "HIGH",
    dueDate: "2026-09-07T22:30:00Z",
    status: "PENDING",
    reminder: true,
    createdAt: "2026-09-07T08:00:00Z",
  },
  {
    id: "task-5",
    title: "Review 1 unclassified expense transaction from morning shopping",
    assignedTo: "Vikram Patil",
    priority: "MEDIUM",
    dueDate: "2026-09-07T18:00:00Z",
    status: "PENDING",
    reminder: true,
    createdAt: "2026-09-07T15:50:00Z",
  },
  {
    id: "task-6",
    title: "Order paper napkin rolls and parcel packaging bags",
    assignedTo: "Sachin More",
    priority: "LOW",
    dueDate: "2026-09-08T10:00:00Z",
    status: "PENDING",
    reminder: false,
    createdAt: "2026-09-07T14:00:00Z",
  },
];

// ── 10. INTELLIGENT KHANAWAL REMINDERS ─────────────────────────────
export const initialReminders: KhanawalReminder[] = [
  {
    id: "rem-1",
    type: "LOW_STOCK",
    title: "Fresh Chicken Re-order (कोंबडी साठा संपत आला)",
    message: "Chicken stock at 2.0 kg (Threshold: 5.0 kg). Order 15kg from Raju Poultry for dinner rush.",
    category: "INVENTORY",
    urgency: "HIGH",
    dueDate: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    recurrence: "DAILY",
    targetRole: "MANAGER",
    isCompleted: false,
    isDismissed: false,
  },
  {
    id: "rem-2",
    type: "SUPPLIER_PAYMENT",
    title: "Mahesh Bhakri Advance Adjustment",
    message: "Mahesh Bhakri Kendra invoice settled against ₹2,000 advance. Final ₹100 cash voucher due.",
    category: "FINANCE",
    urgency: "LOW",
    dueDate: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    recurrence: "ONCE",
    targetRole: "CASHIER",
    isCompleted: false,
    isDismissed: false,
  },
  {
    id: "rem-3",
    type: "FREEZER_MAINTENANCE",
    title: "Deep Freezer #1 Temp Dial Check (-18°C)",
    message: "Verify temperature dial is holding steady at -18°C after compressor maintenance.",
    category: "SAFETY",
    urgency: "CRITICAL",
    dueDate: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    recurrence: "DAILY",
    targetRole: "ADMIN",
    isCompleted: false,
    isDismissed: false,
  },
  {
    id: "rem-4",
    type: "DAILY_CLOSING",
    title: "Night 10-Point Closing Audit & Z-Report",
    message: "Complete 10-point daily closing check before locking cash drawer and print thermal Z-report.",
    category: "OPERATIONS",
    urgency: "MEDIUM",
    dueDate: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    recurrence: "DAILY",
    targetRole: "ALL",
    isCompleted: false,
    isDismissed: false,
  },
];

// ── 10B. LIVE OPERATIONAL NOTIFICATIONS ──────────────────────────────
export const initialNotifications: RestaurantNotification[] = [
  {
    id: "notif-1",
    type: "KOT_READY",
    title: "KOT #12 Ready for Pickup",
    message: "Table 1 (T1-P01): Special Chicken Thali (2) is plated and ready on Dispatch Shelf.",
    category: "SERVICE",
    urgency: "HIGH",
    targetRoles: ["WAITER", "MANAGER", "ADMIN"],
    actionUrl: "/waiter/order/party-01",
    actionLabel: "View Order",
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    metadata: { tableNumber: 1, kotNumber: "KOT-12" },
  },
  {
    id: "notif-2",
    type: "LOW_STOCK",
    title: "Chicken Stock Alert (कोंबडी कमी)",
    message: "Fresh Chicken inventory has fallen to 2.0 kg. Par level is 10.0 kg.",
    category: "INVENTORY",
    urgency: "CRITICAL",
    targetRoles: ["ADMIN", "MANAGER", "CHEF"],
    actionUrl: "/purchases",
    actionLabel: "Fast Purchase",
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-3",
    type: "CHECKLIST_PENDING",
    title: "Kitchen Evening Safety Audit Pending",
    message: "Gas manifold pressure, exhaust hood check & oil trap check not yet logged.",
    category: "MAINTENANCE",
    urgency: "MEDIUM",
    targetRoles: ["ADMIN", "MANAGER", "CHEF"],
    actionUrl: "/checklists",
    actionLabel: "Complete Checklist",
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
];

// ── 11. BANER IT OFFICE GROUP ORDERS ──────────────────────────────
export const initialOfficeOrders: OfficeGroupOrder[] = [
  {
    id: "off-ord-01",
    orderNumber: "OFF-20260907-01",
    companyName: "Persistent Systems IT Group, Baner",
    contactPerson: "Amol Deshmukh",
    contactNumber: "+91 98230 45678",
    pickupDeliveryTime: "2026-09-07T13:30:00Z",
    deliveryType: "PICKUP",
    items: [
      {
        menuItemId: "menu-chicken-thali",
        menuItemName: "Special Chicken Thali",
        quantity: 15,
        unitPrice: 320,
        totalPrice: 4800,
      },
      {
        menuItemId: "menu-mutton-thali",
        menuItemName: "Special Mutton Thali",
        quantity: 8,
        unitPrice: 440,
        totalPrice: 3520,
      },
      {
        menuItemId: "menu-solkadhi",
        menuItemName: "Kolhapuri Solkadhi Glass",
        quantity: 12,
        unitPrice: 40,
        totalPrice: 480,
      },
    ],
    totalAmount: 8800,
    advancePaid: 4000,
    paymentStatus: "PARTIALLY_PAID",
    paymentMethod: "UPI",
    status: "PREPARING",
    specialInstructions: "Pack extra tambda rassa wati + chopped kanda-limbu boxes. Spicy!",
    createdAt: "2026-09-07T10:15:00Z",
  },
  {
    id: "off-ord-02",
    orderNumber: "OFF-20260907-02",
    companyName: "TCS Hinjawadi Phase 1 Team",
    contactPerson: "Sneha Kulkarni",
    contactNumber: "+91 98221 98765",
    pickupDeliveryTime: "2026-09-07T19:45:00Z",
    deliveryType: "DELIVERY",
    deliveryAddress: "Quadron Business Park, Hinjawadi Phase 2, Pune",
    items: [
      {
        menuItemId: "menu-chicken-thali",
        menuItemName: "Special Chicken Thali",
        quantity: 20,
        unitPrice: 320,
        totalPrice: 6400,
      },
      {
        menuItemId: "menu-mutton-thali",
        menuItemName: "Special Mutton Thali",
        quantity: 10,
        unitPrice: 440,
        totalPrice: 4400,
      },
    ],
    totalAmount: 10800,
    advancePaid: 10800,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    status: "ORDERED",
    specialInstructions: "Team dinner order. Include 30 hot Jowar bhakris and separate pandhra rassa.",
    createdAt: "2026-09-07T14:20:00Z",
  },
];

// ── 12. PRICE HISTORY TRENDS ──────────────────────────────────────
export const initialPriceHistory: PriceHistoryRecord[] = [
  {
    id: "ph-1",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    date: "2026-09-01",
    ratePerUnit: 370,
    unit: "kg",
  },
  {
    id: "ph-2",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    date: "2026-09-05",
    ratePerUnit: 380,
    unit: "kg",
    previousRate: 370,
    percentageChange: 2.7,
  },
  {
    id: "ph-3",
    ingredientId: "ing-chicken",
    ingredientName: "Fresh Chicken (कोंबडी)",
    supplierId: "sup-raju-chicken",
    supplierName: "Raju Poultry Farm",
    date: "2026-09-07",
    ratePerUnit: 390,
    unit: "kg",
    previousRate: 380,
    percentageChange: 2.63,
  },
  {
    id: "ph-4",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    date: "2026-09-01",
    ratePerUnit: 750,
    unit: "kg",
  },
  {
    id: "ph-5",
    ingredientId: "ing-mutton",
    ingredientName: "Fresh Mutton (बोकडाचे मटण)",
    supplierId: "sup-prakash-mutton",
    supplierName: "Prakash Goat Mutton Mart",
    date: "2026-09-07",
    ratePerUnit: 770,
    unit: "kg",
    previousRate: 750,
    percentageChange: 2.67,
  },
];

// ── 13. CASH RECONCILIATION LEDGER ────────────────────────────────
export const initialCashLedger: CashLedgerEntry[] = [
  {
    id: "csh-01",
    date: "2026-09-07",
    entryType: "OPENING",
    description: "Morning Cash Float in Drawer",
    inflow: 5000,
    outflow: 0,
    balance: 5000,
    timestamp: "2026-09-07T07:00:00Z",
  },
  {
    id: "csh-02",
    date: "2026-09-07",
    entryType: "SALE",
    description: "Lunch Rush Cash Collections (24 thalis settled)",
    inflow: 7800,
    outflow: 0,
    balance: 12800,
    timestamp: "2026-09-07T14:30:00Z",
  },
  {
    id: "csh-03",
    date: "2026-09-07",
    entryType: "PURCHASE",
    description: "Raju Poultry Farm - 6kg Chicken Cash Payment",
    inflow: 0,
    outflow: 2340,
    balance: 10460,
    referenceId: "pur-20260907-01",
    timestamp: "2026-09-07T08:00:00Z",
  },
  {
    id: "csh-04",
    date: "2026-09-07",
    entryType: "EXPENSE",
    description: "Omkar Electric Works - Kitchen Exhaust Service",
    inflow: 0,
    outflow: 1200,
    balance: 9260,
    referenceId: "exp-20260907-01",
    timestamp: "2026-09-07T11:30:00Z",
  },
  {
    id: "csh-05",
    date: "2026-09-07",
    entryType: "SUPPLIER_PAYMENT",
    description: "Mahesh Kendra - Net balance after ₹2,000 advance adjustment",
    inflow: 0,
    outflow: 100,
    balance: 9160,
    referenceId: "spay-mahesh-settle-01",
    timestamp: "2026-09-07T12:00:00Z",
  },
  {
    id: "csh-06",
    date: "2026-09-07",
    entryType: "STAFF_PAYMENT",
    description: "Bandu Patil - Festival Advance Cash Draw",
    inflow: 0,
    outflow: 2000,
    balance: 7160,
    referenceId: "stf-adv-mahesh",
    timestamp: "2026-09-07T15:00:00Z",
  },
];

// ── 14. UPI RECONCILIATION LEDGER ─────────────────────────────────
export const initialUPILedger: UPILedgerEntry[] = [
  {
    id: "upi-01",
    date: "2026-09-07",
    entryType: "OPENING",
    description: "Opening UPI Bank Balance",
    inflow: 14250,
    outflow: 0,
    balance: 14250,
    timestamp: "2026-09-07T00:00:00Z",
  },
  {
    id: "upi-02",
    date: "2026-09-07",
    entryType: "SALE",
    description: "UPI Soundbox Collections (38 QR Scan Settlements)",
    inflow: 14200,
    outflow: 0,
    balance: 28450,
    utrReference: "SBI4928172918",
    timestamp: "2026-09-07T15:00:00Z",
  },
  {
    id: "upi-03",
    date: "2026-09-07",
    entryType: "EXPENSE",
    description: "Prakash Goat Mutton Mart - 8kg Mutton UPI Transfer",
    inflow: 0,
    outflow: 6160,
    balance: 22290,
    utrReference: "HDFC91823901",
    timestamp: "2026-09-07T08:30:00Z",
  },
  {
    id: "upi-04",
    date: "2026-09-07",
    entryType: "EXPENSE",
    description: "Swastik Kirana - 50kg Indrayani Rice Bag + Masalas",
    inflow: 0,
    outflow: 4850,
    balance: 17440,
    utrReference: "ICIC81729012",
    timestamp: "2026-09-07T10:00:00Z",
  },
];

// ── 15. PAST DAILY CLOSING SNAPSHOTS ──────────────────────────────
export const initialDailyClosings: DailyClosingSnapshot[] = [
  {
    id: "cls-20260904",
    date: "2026-09-04",
    closedAt: "2026-09-04T23:15:00Z",
    closedBy: "Vikram Patil",
    totalSales: 22400,
    cashSales: 9800,
    upiSales: 12600,
    cardSales: 0,
    totalThalisSold: 64,
    chickenThalisSold: 42,
    muttonThalisSold: 22,
    foodPurchases: 6735,
    otherExpenses: 1720,
    supplierPayments: 0,
    staffPayments: 0,
    openingCash: 5000,
    expectedCash: 10330,
    actualCash: 10330,
    cashVariance: 0,
    openingUpi: 12000,
    expectedUpi: 19715,
    actualUpi: 19715,
    upiVariance: 0,
    checklistConfirmed: true,
    checklistItems: { c1: true, c2: true, c3: true, c4: true, c5: true, c6: true, c7: true },
    stockVariances: [],
    notes: "Smooth day, gas refill received and chicken stock balanced.",
  },
  {
    id: "cls-20260905",
    date: "2026-09-05",
    closedAt: "2026-09-05T23:30:00Z",
    closedBy: "Vikram Patil",
    totalSales: 31200,
    cashSales: 12800,
    upiSales: 18400,
    cardSales: 0,
    totalThalisSold: 88,
    chickenThalisSold: 55,
    muttonThalisSold: 33,
    foodPurchases: 11730,
    otherExpenses: 6628,
    supplierPayments: 2000, // Mahesh Advance
    staffPayments: 0,
    openingCash: 5000,
    expectedCash: 7612,
    actualCash: 7612,
    cashVariance: 0,
    openingUpi: 15000,
    expectedUpi: 22230,
    actualUpi: 22230,
    upiVariance: 0,
    checklistConfirmed: true,
    checklistItems: { c1: true, c2: true, c3: true, c4: true, c5: true, c6: true, c7: true },
    stockVariances: [],
    notes: "Deep freezer repaired at 2:30 PM (₹3,800). Temperature holding stable at -18°C.",
  },
  {
    id: "cls-20260906",
    date: "2026-09-06",
    closedAt: "2026-09-06T23:45:00Z",
    closedBy: "Vikram Patil",
    totalSales: 35700,
    cashSales: 14500,
    upiSales: 21200,
    cardSales: 0,
    totalThalisSold: 104,
    chickenThalisSold: 68,
    muttonThalisSold: 36,
    foodPurchases: 7090,
    otherExpenses: 5113,
    supplierPayments: 0,
    staffPayments: 1500, // Cook advance
    openingCash: 5000,
    expectedCash: 14747,
    actualCash: 14747,
    cashVariance: 0,
    openingUpi: 18000,
    expectedUpi: 29850,
    actualUpi: 29850,
    upiVariance: 0,
    checklistConfirmed: true,
    checklistItems: { c1: true, c2: true, c3: true, c4: true, c5: true, c6: true, c7: true },
    stockVariances: [],
    notes: "Heavy Sunday rush. All mutton sold out by 9:45 PM. Cook advance recorded.",
  },
];

